#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: e661f3a
#
Name     : R-crosstalk
Version  : 1.2.1
Release  : 53
URL      : https://cran.r-project.org/src/contrib/crosstalk_1.2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/crosstalk_1.2.1.tar.gz
Summary  : Inter-Widget Interactivity for HTML Widgets
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: R-crosstalk-license = %{version}-%{release}
Requires: R-R6
Requires: R-htmltools
Requires: R-jsonlite
Requires: R-lazyeval
BuildRequires : R-R6
BuildRequires : R-htmltools
BuildRequires : R-jsonlite
BuildRequires : R-lazyeval
BuildRequires : R-shiny
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
with each other, with Shiny or without (i.e. static .html files). Currently
    supports linked brushing and filtering.

%package license
Summary: license components for the R-crosstalk package.
Group: Default

%description license
license components for the R-crosstalk package.


%prep
%setup -q -n crosstalk
pushd ..
cp -a crosstalk buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1700987276

%install
export SOURCE_DATE_EPOCH=1700987276
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-crosstalk
cp %{_builddir}/crosstalk/LICENSE.note %{buildroot}/usr/share/package-licenses/R-crosstalk/6cf67ff73809de8490a65bd826698a1417a9ae0d || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/crosstalk/DESCRIPTION
/usr/lib64/R/library/crosstalk/INDEX
/usr/lib64/R/library/crosstalk/LICENSE
/usr/lib64/R/library/crosstalk/Meta/Rd.rds
/usr/lib64/R/library/crosstalk/Meta/features.rds
/usr/lib64/R/library/crosstalk/Meta/hsearch.rds
/usr/lib64/R/library/crosstalk/Meta/links.rds
/usr/lib64/R/library/crosstalk/Meta/nsInfo.rds
/usr/lib64/R/library/crosstalk/Meta/package.rds
/usr/lib64/R/library/crosstalk/NAMESPACE
/usr/lib64/R/library/crosstalk/NEWS.md
/usr/lib64/R/library/crosstalk/R/crosstalk
/usr/lib64/R/library/crosstalk/R/crosstalk.rdb
/usr/lib64/R/library/crosstalk/R/crosstalk.rdx
/usr/lib64/R/library/crosstalk/help/AnIndex
/usr/lib64/R/library/crosstalk/help/aliases.rds
/usr/lib64/R/library/crosstalk/help/crosstalk.rdb
/usr/lib64/R/library/crosstalk/help/crosstalk.rdx
/usr/lib64/R/library/crosstalk/help/paths.rds
/usr/lib64/R/library/crosstalk/html/00Index.html
/usr/lib64/R/library/crosstalk/html/R.css
/usr/lib64/R/library/crosstalk/lib/bootstrap/bootstrap-grid.min.css
/usr/lib64/R/library/crosstalk/lib/ionrangeslider/css/ion.rangeSlider.css
/usr/lib64/R/library/crosstalk/lib/ionrangeslider/js/ion.rangeSlider.js
/usr/lib64/R/library/crosstalk/lib/ionrangeslider/js/ion.rangeSlider.min.js
/usr/lib64/R/library/crosstalk/lib/ionrangeslider/scss/_base.scss
/usr/lib64/R/library/crosstalk/lib/ionrangeslider/scss/_mixins.scss
/usr/lib64/R/library/crosstalk/lib/ionrangeslider/scss/shiny.scss
/usr/lib64/R/library/crosstalk/lib/jquery/jquery-AUTHORS.txt
/usr/lib64/R/library/crosstalk/lib/jquery/jquery.js
/usr/lib64/R/library/crosstalk/lib/jquery/jquery.min.js
/usr/lib64/R/library/crosstalk/lib/jquery/jquery.min.map
/usr/lib64/R/library/crosstalk/lib/selectize/css/selectize.bootstrap3.css
/usr/lib64/R/library/crosstalk/lib/selectize/js/selectize.min.js
/usr/lib64/R/library/crosstalk/lib/strftime/strftime-min.js
/usr/lib64/R/library/crosstalk/tests/testthat.R
/usr/lib64/R/library/crosstalk/tests/testthat/test-built.css.R
/usr/lib64/R/library/crosstalk/tests/testthat/test-crosstalk.R
/usr/lib64/R/library/crosstalk/www/css/crosstalk.min.css
/usr/lib64/R/library/crosstalk/www/js/crosstalk.js
/usr/lib64/R/library/crosstalk/www/js/crosstalk.js.map
/usr/lib64/R/library/crosstalk/www/js/crosstalk.min.js
/usr/lib64/R/library/crosstalk/www/js/crosstalk.min.js.map
/usr/lib64/R/library/crosstalk/www/scss/crosstalk.scss

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-crosstalk/6cf67ff73809de8490a65bd826698a1417a9ae0d
